# -*- coding: utf-8 -*-
"""logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S6dtH5EnLAZ4nCTfywB8UcCHgepteulZ

<h2 style="color:green" align="center">Predicting if a person would buy life insurnace based on his age using logistic regression</h2>
"""

!pip install streamlit

"""Above is a binary logistic regression problem as there are only two possible outcomes (i.e. if person buys insurance or he/she doesn't)."""

import pandas as pd
import streamlit as st
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Page Configuration
st.set_page_config(
    page_title="Life Insurance Buying Prediction",
    page_icon="💸💰",
    layout="centered"
)

st.title("💸💰 Life Insurance Prediction")
st.write("Predict whether a person will buy life insurance based on age using Logistic Regression")

# Load dataset
df = pd.read_csv("insurance_data.csv")

st.subheader("Dataset")
st.dataframe(df)

# Features and target
X = df[['age']]
y = df['bought_insurance']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model = LogisticRegression()
model.fit(X_train, y_train)

# Model accuracy
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

st.subheader("Model Accuracy")
st.write(f"Accuracy: {accuracy * 100:.2f}%")

# User input
st.subheader("Enter Person's Age")
age = st.number_input(
    "Age",
    min_value=10,
    max_value=75,
    value=30,
    step=1
)

# Prediction
if st.button("Predict Insurance Purchase"):
    prediction = model.predict([[age]])[0]
    probability = model.predict_proba([[age]])[0]

    st.subheader("Prediction Result")

    if prediction == 1:
        st.success("This person is likely to BUY life insurance.")
    else:
        st.error("This person is NOT likely to buy life insurance.")

    st.write(f"Probability of NOT buying insurance: {probability[0]:.2f}")
    st.write(f"Probability of BUYING insurance: {probability[1]:.2f}")